### ISSUE TITLE
Getting the derivative of the moon's altitude

### ISSUE THREAD

**Issue by vicesalles** [darkskyapp/astro#3]
Hi @ironwallaby can you give me any tip for getting the moon's altitude derivative using astro?

**Comment by ironwallaby** [comment]
Here's an example that should do what you're looking for (to a reasonably high degree of accuracy, though it's not as accurate or efficient as it could be!):

```javascript
"use strict";
const astro = require("astro");

function moon_rising_or_setting(date, lat, lon) {
  /* Astro uses julian dates, not Date objects. */
  date = astro.date_to_julian(date);

  /* Astro uses radians, not degrees. */
  lat *= Math.PI / 180;
  lon *= Math.PI / 180;

  /* HACK: Find the altitude a few minutes ago, and the altitude a few minutes
   * from now, and use the difference to determine whether the moon is rising
   * or setting. This should be accurate except maybe when the moon is at its
   * highest or lowest point in the sky. It would be nicer, however, if astro
   * supported an altitude_derivative function! */
  const altitude_before = astro.lunar.altitude(date - 0.005, lat, lon),
        altitude_after  = astro.lunar.altitude(date + 0.005, lat, lon);
  return ((altitude_after - altitude_before) >= 0) ? "rising" : "setting";
}

console.log(moon_rising_or_setting(new Date(), +42, -73));
```

However, I'd like to keep this ticket open, since supporting `astro.lunar.altitude_derivative` seems like a good idea, though I need to work out the math behind it!

**Comment by vicesalles** [comment]
Thank you very much @ironwallaby It worked and then I realized I wasn't looking for this. I'm very sorry, just discovered that what I'm actually looking for is called the inclination of the moon https://en.wikipedia.org/wiki/Orbit_of_the_Moon#Nodes 
I'm interested on this because when the moon is on the nodes, as when it's in the peregee, it's not a good idea to do gardening works.

If I make any advance i'll post it here. 

greetings
