### ISSUE TITLE
Make subcomputations cacheable

### ISSUE THREAD

**Issue by ironwallaby** [darkskyapp/astro#4]
I propose refactoring the interface to Astro to cache computations and subcomputations.

I would like the following (in addition to the normal, uncached interfaces if you want to roll like that):

```
class astro.solar.Time {
  constructor(time_julian)
  get mean_anomaly
  get longitude
  get obliquity
  get right_ascension
  get declination
  get distance
  event(lat, lon) { return new Event(this, lat, lon) }
}
class astro.solar.Event {
  constructor(time, lat, lon)
  get elevation
  get azimuth
  get hour_angle
}
```

Each of these things should memoize the relevant fields created as part of the computation.

In this way, most of the work involved in computing these properties is cached, and those caches are reused as much as possible. While objects get created, I'm fairly sure that the object allocation is much cheaper than the tons and tons of trig that we do in our other libraries.

**Comment by nonrenewable** [comment]
I'm pretty sure this just came up when testing `v3/events` endpoint - the three lunar properties we now support take up 50% of the time for a request so per @ironwallaby this might be a good way to improve their performance. (or i picked the wrong ticket to put this against 🍇 )
