### ISSUE TITLE
Sunset time incorrect in Roane County, TN

### ISSUE THREAD

**Issue by estraight4490** [darkskyapp/astro#5]
Sunset was reported in the app and website for 5:13PM however, other sources say that sunset is at 6:11PM.

**Comment by ironwallaby** [comment]
I assume this is for today?

Roane County, TN is ZIP code 37748.

**Comment by estraight4490** [comment]
Yes, it's for 2/7/18.

**Comment by ironwallaby** [comment]
Astro is returning the right data, but API V2 is not. V2 is using suncalc, though! Moving this ticket to API V2.

**Comment by ironwallaby** [comment]
https://github.com/darkskyapp/api_v2/issues/64

**Comment by ironwallaby** [comment]
I switched the API to `astro` but still see this issue:

```> pretty.date(astro.julian_to_ms(astro.solar.set(astro.unix_to_julian(1517983200 + 43200), 35.8468 * (Math.PI / 180), -84.6665 * (Math.PI / 180))), "America/Chicago")
'2018-02-07T17:13:20.185-0600'
```

Further, I can confirm that 6:12 PM should be correct:

http://aa.usno.navy.mil/rstt/onedaytable?ID=AA&year=2018&month=2&day=7&state=TN&place=Kingston

**Comment by ironwallaby** [comment]
Ooh! Actually, Kingston is EST? Gonna move this to `tz-lookup`

**Comment by ironwallaby** [comment]
https://github.com/darkskyapp/tz-lookup/issues/18
